name: Continuous Integration

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install the mvola package
      run: python setup.py install --force --user
  
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Unit test for messenger api
      run: CONSUMER_KEY=${{secrets.CONSUMER_KEY}} SECRET_KEY=${{secrets.SECRET_KEY}} pytest